<?php //echo '<pre>';print_r($this->getCollection()->getItems());die;?>

<table class="grid-table" border="1" width="100%">
    <thead>
        <tr>
            <th>Test ID</th>
            <th>Title</th>
            <th>Price</th>
            <th>Status</th>
            <th>Created At</th>
            <th>Is Active</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->getCollection()->getItems() as $item): ?>
            <tr>
                <td><?php echo $item->getId(); ?></td>
                <td><?php echo $item->getTitle(); ?></td>
                <td><?php echo $item->getPrice(); ?></td>
                <td><?php echo $item->getStatus(); ?></td>
                <td><?php echo $item->getCreatedAt(); ?></td>
                <td><?php echo $item->getIsActive(); ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
